-- 코드를 입력하세요
SELECT A.USER_ID
     , A.NICKNAME
     , SUM(B.PRICE) AS 'TOTAL_SALES'
  FROM USED_GOODS_USER A
  LEFT JOIN USED_GOODS_BOARD B ON A.USER_ID = B.WRITER_ID
 WHERE STATUS = 'DONE'
 GROUP BY USER_ID
HAVING SUM(B.PRICE) >= 700000
 ORDER BY TOTAL_SALES ASC;