-- 코드를 입력하세요
SELECT A.MEMBER_NAME
     , B.REVIEW_TEXT
     , TO_CHAR(B.REVIEW_DATE, 'YYYY-MM-DD')   AS REVIEW_DATE
  FROM MEMBER_PROFILE A
  LEFT JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
 WHERE A.MEMBER_ID IN 
       (SELECT MEMBER_ID
          FROM (SELECT MEMBER_ID
                     , COUNT(MEMBER_ID)
                     , DENSE_RANK () OVER (ORDER BY COUNT(MEMBER_ID) DESC) AS RK
                 FROM REST_REVIEW
                GROUP BY MEMBER_ID
               ) A
         WHERE RK = 1
       )
 ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;