-- 코드를 입력하세요
SELECT A.APNT_NO
     , P.PT_NAME
     , P.PT_NO
     , D.MCDP_CD
     , D.DR_NAME
     , A.APNT_YMD
  FROM PATIENT P
 INNER JOIN APPOINTMENT A ON A.PT_NO = P.PT_NO
 INNER JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
 WHERE A.APNT_YMD BETWEEN '2022-04-13 00:00:00' AND '2022-04-13 23:59:59'
   AND A.APNT_CNCL_YN = 'N'
   AND A.MCDP_CD = 'CS'
 ORDER BY A.APNT_YMD;